import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Container from '@mui/material/Container'

export default function Home() {
  return (
    <Container className={styles.container} bg-color="primary.main">
      <Head>
        <title>WINterview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          An.
        </h1>
      </main>
    </Container>
  )
}
